version: '3.1'
services:
  db:
    image: mysql
    platform: linux/amd64
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: bseidf40
    ports:
    - "3309:3309"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data:
